# Generated by Django 3.0.5 on 2020-04-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('artist', models.CharField(max_length=1000)),
                ('mp4', models.FileField(upload_to='music/')),
                ('cover', models.ImageField(upload_to='cover/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
