# Generated by Django 3.0.5 on 2020-04-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='mp4',
            new_name='mp3',
        ),
    ]
