# Generated by Django 3.0.5 on 2020-04-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_music_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.TextField(max_length=5000),
        ),
    ]
