# Generated by Django 3.0.5 on 2020-04-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200415_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_record', models.FileField(upload_to='', verbose_name='sound_record/')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Music')),
            ],
        ),
    ]
