# Generated by Django 3.0.5 on 2020-04-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='merged_record',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='voice_record',
            field=models.FileField(upload_to='sound_record/'),
        ),
    ]
