# Generated by Django 3.0.5 on 2020-04-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200418_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
